object Versions {
    const val jvmPlugin = "1.7.0"
    const val libraryPlugin = "8.0.0"
    const val androidPlugin = "1.7.0"
    const val androidGradlePlugin = "8.0.1"

    const val androidxNavigation = "2.5.3"
    const val androidxAppcompat = "1.6.1"
    const val androidxFragmentKtx = "1.5.2"
    const val androidxCoreKtx = "1.10.1"
    const val androidxActivity = "1.5.1"
    const val androidxLifecycle = "2.5.1"
    const val androidxWearCompose = "1.0.2"

    const val compose = "1.2.1"
    const val composeCompiler = "1.2.0"
    const val composeAnimation = "1.4.3"

    const val stdlibJdk = "1.8.0"
    const val accompanistPager = "0.22.0-rc"
    const val espresso = "3.5.1"
    const val extJUnit = "1.1.5"
    const val junit = "4.13.2"
    const val googleMaterial = "1.9.0"
    const val jacocoAnt = "0.8.8"
    const val playServicesWearable = "17.1.0"
    const val desugarJdkLibs = "1.1.5"
    const val ktlint = "0.46.1"
    const val kotlin = "1.7.0"
    const val kotlinx = "1.6.4"
}
